version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - whitespace
    - nilerr
    - prealloc
    - copyloopvar
  disable:
    - gocyclo
    - funlen
    - gocognit
  exclusions:
    paths:
      - vendor
      - bin

formatters:
  enable:
    - goimports
    - gofmt
  exclusions:
    paths:
      - vendor
      - bin
